version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 8443:443
      - 80:80
    restart: always
    secrets:
      - server.key
    
secrets:
  server.key:
    file: ../secrets/server.key

