services:
  
  mariadb:
    container_name: mariadb 
    build: .
    restart: always
    secrets:
      - db_root_password
      - db_user_password
    env_file:
      - ../../.env
    network_mode: bridge   

secrets:
  db_root_password:
    file: ../../../secrets/db_root_password.txt
  db_user_password:
    file: ../../../secrets/db_user_password.txt
  wp_admin_password:
    file: ../../../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../../../secrets/wp_user_password.txt
